name: Check pull request
on:
  pull_request:
    branches:
    - main
    - develop*

jobs:
  Build_MERIDIAN_LITE_ESP32:
    uses: ./.github/workflows/_WORKFLOW_CALL_RunningPlatformIO.yml
    with:
      board_env: Meridian_LITE_ESP32
      firmware_name: Meridian_LITE_for_ESP32
  Build_MERIDIAN_TWIN_ESP32:
    uses: ./.github/workflows/_WORKFLOW_CALL_RunningPlatformIO.yml
    with:
      board_env: Meridian_TWIN_ESP32
      firmware_name: Meridian_TWIN_for_ESP32
  Build_MERIDIAN_TWIN_TEENSY:
    uses: ./.github/workflows/_WORKFLOW_CALL_RunningPlatformIO.yml
    with:
      board_env: Meridian_TWIN_Teensy
      firmware_name: Meridian_TWIN_for_Teensy
      ext_name: hex
  Build_MERIDIAN_LITE_M5STACK_ATOM_S3:
    uses: ./.github/workflows/_WORKFLOW_CALL_RunningPlatformIO.yml
    with:
      board_env: Meridian_LITE_M5StackAtomS3
      firmware_name: Meridian_LITE_for_M5StackAtomS3
  Build_MERIDIAN_LITE_M5STACK_ATOM_LITE:
    uses: ./.github/workflows/_WORKFLOW_CALL_RunningPlatformIO.yml
    with:
      board_env: Meridian_LITE_M5StackAtomLite
      firmware_name: Meridian_LITE_for_M5StackAtomLite
  Build_Meridian_LITE_RaspberryPiPico:
    uses: ./.github/workflows/_WORKFLOW_CALL_RunningPlatformIO.yml
    with:
      board_env: Meridian_LITE_RaspberryPiPico
      firmware_name: Meridian_LITE_RaspberryPiPico
